export type PartOfSpeech = "verb" | "noun" | "adj" | "adv";

export type SeedCardRecord = {
  sp: string;
  en: string;
  type: PartOfSpeech;
  freq: number;
};

export const SEED_CARD_DECK: SeedCardRecord[] = [
  { sp: "decir", en: "to say / to tell", type: "verb", freq: 932 },
  { sp: "preguntar", en: "to ask / to question", type: "verb", freq: 156 },
  { sp: "gritar", en: "to shout / to scream", type: "verb", freq: 82 },
  { sp: "mirar", en: "to look at / to watch", type: "verb", freq: 83 },
  { sp: "abrir", en: "to open", type: "verb", freq: 75 },
  { sp: "levantar", en: "to raise / to lift", type: "verb", freq: 49 },
  { sp: "coger", en: "to grab / to take (Spain)", type: "verb", freq: 43 },
  { sp: "responder", en: "to respond / to reply", type: "verb", freq: 40 },
  { sp: "susurrar", en: "to whisper", type: "verb", freq: 30 },
  { sp: "añadir", en: "to add / to say furthermore", type: "verb", freq: 33 },
  { sp: "contestar", en: "to answer / to reply", type: "verb", freq: 30 },
  { sp: "sacar", en: "to take out / to pull out", type: "verb", freq: 38 },
  { sp: "dejar", en: "to let / to leave behind", type: "verb", freq: 29 },
  { sp: "llegar", en: "to arrive / to reach", type: "verb", freq: 31 },
  { sp: "acercar", en: "to approach / to bring closer", type: "verb", freq: 35 },
  { sp: "volver", en: "to return / to go back", type: "verb", freq: 41 },
  { sp: "entrar", en: "to enter / to go in", type: "verb", freq: 28 },
  { sp: "correr", en: "to run", type: "verb", freq: 37 },
  { sp: "hablar", en: "to speak / to talk", type: "verb", freq: 58 },
  { sp: "escuchar", en: "to listen / to hear", type: "verb", freq: 25 },
  { sp: "intentar", en: "to try / to attempt", type: "verb", freq: 22 },
  { sp: "parecer", en: "to seem / to appear", type: "verb", freq: 124 },
  { sp: "recordar", en: "to remember / to remind", type: "verb", freq: 20 },
  { sp: "caer", en: "to fall", type: "verb", freq: 28 },
  { sp: "empujar", en: "to push / to shove", type: "verb", freq: 14 },
  { sp: "murmurar", en: "to murmur / to mutter", type: "verb", freq: 18 },
  { sp: "desaparecer", en: "to disappear (wizard context: vanish)", type: "verb", freq: 20 },
  { sp: "transformar", en: "to transform / to change form (spell)", type: "verb", freq: 16 },
  { sp: "atravesar", en: "to cross / to pass through", type: "verb", freq: 12 },
  { sp: "lanzar", en: "to throw / to launch / to cast (a spell)", type: "verb", freq: 18 },

  // NOUNS
  { sp: "varita", en: "wand (wizarding tool for casting spells)", type: "noun", freq: 113 },
  { sp: "cámara", en: "chamber / camera", type: "noun", freq: 103 },
  { sp: "magia", en: "magic [mágico]", type: "noun", freq: 65 },
  { sp: "puerta", en: "door / gate [abrir]", type: "noun", freq: 143 },
  { sp: "ojo", en: "eye [mirar]", type: "noun", freq: 164 },
  { sp: "cabeza", en: "head / mind [pensar]", type: "noun", freq: 135 },
  { sp: "mano", en: "hand [coger]", type: "noun", freq: 82 },
  { sp: "voz", en: "voice [hablar]", type: "noun", freq: 188 },
  { sp: "cara", en: "face / expression [mirar]", type: "noun", freq: 86 },
  { sp: "suelo", en: "floor / ground", type: "noun", freq: 93 },
  { sp: "castillo", en: "castle (Hogwarts setting)", type: "noun", freq: 50 },
  { sp: "sangre", en: "blood (key HP theme: blood purity)", type: "noun", freq: 48 },
  { sp: "serpiente", en: "serpent / snake [Slytherin symbol]", type: "noun", freq: 47 },
  { sp: "sombrero", en: "hat (the Sorting Hat in HP context)", type: "noun", freq: 47 },
  { sp: "araña", en: "spider [Aragog's species]", type: "noun", freq: 41 },
  { sp: "elfo", en: "elf (house-elf: wizarding servant)", type: "noun", freq: 29 },
  { sp: "mago", en: "wizard / sorcerer [magia]", type: "noun", freq: 42 },
  { sp: "poción", en: "potion (brewed magical liquid)", type: "noun", freq: 33 },
  { sp: "heredero", en: "heir / inheritor [heredar]", type: "noun", freq: 31 },
  { sp: "basilisco", en: "basilisk (legendary lethal serpent)", type: "noun", freq: 31 },
  { sp: "corredor", en: "corridor / hallway [castle passages]", type: "noun", freq: 40 },
  { sp: "diario", en: "diary / daily [Riddle's diary, key plot item]", type: "noun", freq: 69 },
  { sp: "secreto", en: "secret [Chamber of Secrets]", type: "noun", freq: 52 },
  { sp: "mundo", en: "world [el mundo mágico = wizarding world]", type: "noun", freq: 39 },
  { sp: "palaba", en: "word [palabras mágicas = magic words]", type: "noun", freq: 38 },
  { sp: "silencio", en: "silence / quiet [silenciar]", type: "noun", freq: 44 },
  { sp: "equipo", en: "team / equipment [Quidditch teams]", type: "noun", freq: 38 },
  { sp: "ventana", en: "window [abrir la ventana]", type: "noun", freq: 38 },
  { sp: "escalera", en: "stairs / staircase [castle stairs]", type: "noun", freq: 32 },
  { sp: "dormitorio", en: "dormitory / bedroom [Gryffindor dorm]", type: "noun", freq: 30 },
  { sp: "gafa", en: "glasses / spectacles [Harry's trademark]", type: "noun", freq: 30 },
  { sp: "nariz", en: "nose [nariz aguileña = hooked nose]", type: "noun", freq: 31 },
  { sp: "brazo", en: "arm [el brazo roto = broken arm]", type: "noun", freq: 41 },
  { sp: "pie", en: "foot / feet (standing point) [de pie = standing]", type: "noun", freq: 34 },
  { sp: "techo", en: "ceiling / roof [enchanted ceiling at Hogwarts]", type: "noun", freq: 32 },
  { sp: "rostro", en: "face / countenance (literary, more formal than cara)", type: "noun", freq: 33 },
  { sp: "multitud", en: "crowd / multitude [multitudinario]", type: "noun", freq: 31 },
  { sp: "instante", en: "instant / moment [al instante = instantly]", type: "noun", freq: 38 },
  { sp: "sonrisa", en: "smile [sonreír]", type: "noun", freq: 39 },
  { sp: "mirada", en: "gaze / look / glance [mirar]", type: "noun", freq: 49 },
  { sp: "túnica", en: "robe / tunic (wizarding garment)", type: "noun", freq: 41 },
  { sp: "curso", en: "school year / course [second year at Hogwarts]", type: "noun", freq: 43 },
  { sp: "ruido", en: "noise / sound [hacer ruido]", type: "noun", freq: 41 },
  { sp: "camino", en: "path / road / way [allanar el camino]", type: "noun", freq: 28 },
  { sp: "piedra", en: "stone [Philosopher's Stone, prev. book]", type: "noun", freq: 28 },
  { sp: "noche", en: "night [de noche = at night]", type: "noun", freq: 58 },
  { sp: "vida", en: "life [en vida = alive]", type: "noun", freq: 28 },
  { sp: "nombre", en: "name [el-que-no-debe-ser-nombrado]", type: "noun", freq: 34 },
  { sp: "idea", en: "idea / plan [buena idea]", type: "noun", freq: 32 },
  { sp: "manera", en: "manner / way [de ninguna manera = no way]", type: "noun", freq: 31 },
  { sp: "lugar", en: "place / location [en su lugar = instead]", type: "noun", freq: 48 },
  { sp: "gente", en: "people / folk [la gente del colegio]", type: "noun", freq: 48 },
  { sp: "familia", en: "family [familia Weasley = the Weasley family]", type: "noun", freq: 44 },
  { sp: "libro", en: "book [libros de texto = textbooks]", type: "noun", freq: 50 },
  { sp: "alumno", en: "student / pupil [alumnos de Hogwarts]", type: "noun", freq: 42 },
  { sp: "tiempo", en: "time / weather [con el tiempo = in time]", type: "noun", freq: 77 },
  { sp: "colegio", en: "school (here: Hogwarts) [colegial]", type: "noun", freq: 103 },
  { sp: "padre", en: "father / parent [padre mágico]", type: "noun", freq: 54 },
  { sp: "pelo", en: "hair [pelo revuelto = messy hair like Harry's]", type: "noun", freq: 43 },
  { sp: "boca", en: "mouth [boca abierta = open-mouthed]", type: "noun", freq: 50 },
  { sp: "prisa", en: "hurry / haste [darse prisa = to hurry]", type: "noun", freq: 30 },
  { sp: "frente", en: "forehead / front [la cicatriz en la frente]", type: "noun", freq: 29 },
  { sp: "muchacho", en: "boy / lad / youngster", type: "noun", freq: 29 },
  { sp: "aire", en: "air / atmosphere [en el aire = in the air]", type: "noun", freq: 49 },
  { sp: "minuto", en: "minute [en pocos minutos = in a few minutes]", type: "noun", freq: 32 },
  { sp: "tarde", en: "afternoon / late (time adverb) [por la tarde]", type: "noun", freq: 31 },
  { sp: "mañana", en: "morning / tomorrow [mañana por la mañana]", type: "noun", freq: 28 },
  { sp: "punto", en: "point / dot / period [en ese punto = at that point]", type: "noun", freq: 28 },
  { sp: "cama", en: "bed [irse a la cama = to go to bed]", type: "noun", freq: 55 },
  { sp: "sala", en: "common room / hall / lounge [sala común]", type: "noun", freq: 55 },
  { sp: "mesa", en: "table / desk [mesa del comedor]", type: "noun", freq: 65 },
  { sp: "forma", en: "form / shape / way [de alguna forma]", type: "noun", freq: 39 },
  { sp: "clase", en: "class / classroom / kind [clase de pociones]", type: "noun", freq: 74 },
  { sp: "muggle", en: "Muggle (non-magical person, HP term)", type: "noun", freq: 41 },
  { sp: "coche", en: "car (the flying Ford Anglia)", type: "noun", freq: 95 },
  { sp: "casa", en: "house (also Hogwarts houses) [Gryffindor]", type: "noun", freq: 80 },

  // ADJECTIVES
  { sp: "mágico", en: "magical / magic [magia]", type: "adj", freq: 44 },
  { sp: "grande", en: "big / great / grand [grandioso]", type: "adj", freq: 95 },
  { sp: "seguro", en: "safe / sure / certain [asegurar]", type: "adj", freq: 31 },
  { sp: "fuerte", en: "strong / loud / hard [fortalecer]", type: "adj", freq: 36 },
  { sp: "extraño", en: "strange / foreign / odd [extrañar]", type: "adj", freq: 25 },
  { sp: "oscuro", en: "dark / obscure [oscurecer] (dark arts context)", type: "adj", freq: 22 },
  { sp: "pequeño", en: "small / little / young [pequeñez]", type: "adj", freq: 26 },
  { sp: "enorme", en: "enormous / huge [enormidad]", type: "adj", freq: 18 },
  { sp: "asustado", en: "scared / frightened [asustar]", type: "adj", freq: 14 },
  { sp: "pálido", en: "pale / pallid [palidecer]", type: "adj", freq: 16 },
  { sp: "único", en: "unique / only / sole [unicidad]", type: "adj", freq: 29 },
  { sp: "horrible", en: "horrible / dreadful / awful", type: "adj", freq: 14 },
  { sp: "segundo", en: "second (ordinal) [segundo año = second year]", type: "adj", freq: 35 },
  { sp: "primero", en: "first / primary [primera vez = first time]", type: "adj", freq: 32 },
  { sp: "completo", en: "complete / entire / full [completamente]", type: "adj", freq: 38 },
  { sp: "negro", en: "black [el gato negro de la señora Norris]", type: "adj", freq: 20 },
  { sp: "blanco", en: "white / blank [página en blanco]", type: "adj", freq: 15 },
  { sp: "plateado", en: "silver / silvery [platear] (Nearly Headless Nick)", type: "adj", freq: 12 },
  { sp: "frío", en: "cold / cool [enfriar] (cold dungeons of Slytherin)", type: "adj", freq: 18 },
  { sp: "brillante", en: "brilliant / shining / glowing [brillar]", type: "adj", freq: 14 },
  { sp: "tembloroso", en: "trembling / shaky [temblar]", type: "adj", freq: 10 },
  { sp: "ansioso", en: "anxious / eager / keen [ansiar]", type: "adj", freq: 10 },
  { sp: "nervioso", en: "nervous / anxious [nerviosismo]", type: "adj", freq: 15 },
  { sp: "silencioso", en: "silent / quiet [silencio]", type: "adj", freq: 14 },
  { sp: "doloroso", en: "painful / distressing [doler]", type: "adj", freq: 10 },
  { sp: "encantado", en: "enchanted / delighted (lit: under a spell) [encantar]", type: "adj", freq: 12 },
  { sp: "decapitado", en: "beheaded / decapitated [decapitar] (Nearly-Headless Nick)", type: "adj", freq: 35 },
  { sp: "plateado", en: "silver-colored / silvery [plata]", type: "adj", freq: 12 },
  { sp: "poderoso", en: "powerful / mighty [poder]", type: "adj", freq: 12 },
  { sp: "verdadero", en: "true / real / genuine [verdad]", type: "adj", freq: 14 },
  { sp: "malvado", en: "wicked / evil / villainous [maldad]", type: "adj", freq: 10 },
  { sp: "muggle", en: "Muggle (non-magical — also used as adj)", type: "adj", freq: 37 },
  { sp: "famoso", en: "famous / renowned [fama] (Lockhart is famoso)", type: "adj", freq: 14 },
  { sp: "inmóvil", en: "motionless / still / immobile [moverse]", type: "adj", freq: 12 },
  { sp: "petrificado", en: "petrified / frozen in fear (lit: turned to stone) [petrificar]", type: "adj", freq: 20 },
  { sp: "grande", en: "big / great / large (gran before noun = great)", type: "adj", freq: 46 },
  { sp: "tío", en: "uncle (tío Vernon = Uncle Vernon; colloquial: guy/dude)", type: "noun", freq: 45 },
  { sp: "oído", en: "ear / inner hearing (tocar de oído = to play by ear)", type: "noun", freq: 45 },
  { sp: "familia", en: "family", type: "noun", freq: 44 },
  { sp: "silencio", en: "silence / quiet (en silencio = in silence)", type: "noun", freq: 44 },
  { sp: "curso", en: "school year / course (segundo curso = second year)", type: "noun", freq: 43 },
  { sp: "salir", en: "to leave / to go out / to exit", type: "verb", freq: 43 },
  { sp: "pelo", en: "hair (pelo revuelto = messy hair, like Harry's)", type: "noun", freq: 43 },
  { sp: "mago", en: "wizard / sorcerer / magician", type: "noun", freq: 42 },
  { sp: "alumno", en: "student / pupil (alumnos de Hogwarts = Hogwarts students)", type: "noun", freq: 42 },
  { sp: "araña", en: "spider (Aragog and his colony of Acromantulas)", type: "noun", freq: 41 },
  { sp: "muggle", en: "Muggle (non-magical person — HP-specific term)", type: "noun", freq: 41 },
  { sp: "ruido", en: "noise / sound (hacer ruido = to make noise)", type: "noun", freq: 41 },
  { sp: "brazo", en: "arm (el brazo roto = the broken arm — Lockhart's blunder)", type: "noun", freq: 41 },
  { sp: "volver", en: "to return / to come back / to go back", type: "verb", freq: 41 },
  { sp: "túnica", en: "robe / tunic (the standard wizarding garment)", type: "noun", freq: 41 },
  { sp: "corredor", en: "corridor / hallway / passage (castle corridors)", type: "noun", freq: 40 },
  { sp: "año", en: "year (este año = this year; años = years)", type: "noun", freq: 40 },
  { sp: "mundo", en: "world (el mundo mágico = the wizarding world)", type: "noun", freq: 39 },
  { sp: "forma", en: "form / shape / way (de esta forma = in this way)", type: "noun", freq: 39 },
  { sp: "sonrisa", en: "smile (una amplia sonrisa = a broad smile)", type: "noun", freq: 39 },
  { sp: "hora", en: "hour / time of day (¿qué hora es? = what time is it?)", type: "noun", freq: 38 },
  { sp: "palabra", en: "word (palabras mágicas = magic words)", type: "noun", freq: 38 },
  { sp: "equipo", en: "team / equipment (equipo de Quidditch = Quidditch team)", type: "noun", freq: 38 },
  { sp: "instante", en: "instant / moment (al instante = instantly)", type: "noun", freq: 38 },
  { sp: "ventana", en: "window", type: "noun", freq: 38 },
  { sp: "pasar", en: "to pass / to happen / to spend time (¿qué pasa? = what's happening?)", type: "verb", freq: 37 },
  { sp: "correr", en: "to run / to rush", type: "verb", freq: 37 },
  { sp: "fuerte", en: "strong / loud / hard (un golpe fuerte = a hard blow)", type: "adj", freq: 36 },
  { sp: "decapitado", en: "beheaded / decapitated (Nearly Headless Nick's defining condition)", type: "adj", freq: 35 },
  { sp: "nombre", en: "name (el-que-no-debe-ser-nombrado = He-Who-Must-Not-Be-Named)", type: "noun", freq: 34 },
  { sp: "pie", en: "foot (de pie = standing up; a pie = on foot)", type: "noun", freq: 34 },
  { sp: "cuidado", en: "care / caution (¡ten cuidado! = be careful!)", type: "noun", freq: 34 },
  { sp: "bludger", en: "Bludger (enchanted iron ball used in Quidditch to knock players off brooms)", type: "noun", freq: 34 },
  { sp: "rostro", en: "face / countenance (literary; more formal than cara)", type: "noun", freq: 33 },
  { sp: "poción", en: "potion (a brewed magical liquid; clase de Pociones = Potions class)", type: "noun", freq: 33 },
  { sp: "dar", en: "to give / to strike / to yield (dar un paso = to take a step)", type: "verb", freq: 32 },
  { sp: "techo", en: "ceiling / roof (el techo encantado del Gran Comedor = the enchanted ceiling)", type: "noun", freq: 32 },
  { sp: "escalera", en: "stairs / staircase (the moving staircases of Hogwarts)", type: "noun", freq: 32 },
  { sp: "idea", en: "idea / plan (buena idea = good idea)", type: "noun", freq: 32 },
  { sp: "minuto", en: "minute (en pocos minutos = in a few minutes)", type: "noun", freq: 32 },
  { sp: "primero", en: "first / primary (por primera vez = for the first time)", type: "adj", freq: 32 },
  { sp: "heredero", en: "heir / inheritor (el heredero de Slytherin = the Heir of Slytherin)", type: "noun", freq: 31 },
  { sp: "basilisco", en: "basilisk (the monstrous serpent living in the Chamber of Secrets)", type: "noun", freq: 31 },
  { sp: "nariz", en: "nose (nariz aguileña = hooked nose, like Snape's)", type: "noun", freq: 31 },
  { sp: "multitud", en: "crowd / multitude", type: "noun", freq: 31 },
  { sp: "seguro", en: "safe / sure / certain (estar seguro = to be sure)", type: "adj", freq: 31 },
  { sp: "tarde", en: "afternoon / late (por la tarde = in the afternoon)", type: "noun", freq: 31 },
  { sp: "manera", en: "manner / way (de ninguna manera = no way; in no way)", type: "noun", freq: 31 },
  { sp: "llegar", en: "to arrive / to reach (llegar a tiempo = to arrive on time)", type: "verb", freq: 31 },

  // ── BATCH 3 (words 101–200 by corpus frequency, normalized) ──
  { sp: "ningún", en: "no / none / not any (ningún mago = no wizard)", type: "adj", freq: 42 },
  { sp: "embargo", en: "sin embargo = however / nevertheless (B2 discourse connector)", type: "noun", freq: 40 },
  { sp: "atrás", en: "behind / back / backwards (echar atrás = to back away)", type: "adv", freq: 34 },
  { sp: "fin", en: "end / purpose (al fin = at last; por fin = finally; a fin de = in order to)", type: "noun", freq: 34 },
  { sp: "medio", en: "middle / half / means (en medio de = in the middle of; medio dormido = half asleep)", type: "noun", freq: 32 },
  { sp: "oír", en: "to hear (¿oyes eso? = do you hear that? — Harry hears the Basilisk)", type: "verb", freq: 32 },
  { sp: "dormitorio", en: "dormitory / bedroom (dormitorio de Gryffindor = Gryffindor dormitory)", type: "noun", freq: 30 },
  { sp: "repente", en: "de repente = suddenly / all of a sudden (B2 adverbial phrase)", type: "noun", freq: 30 },
  { sp: "prisa", en: "hurry / haste (darse prisa = to hurry; tener prisa = to be in a hurry)", type: "noun", freq: 30 },
  { sp: "elfo", en: "elf (elfo doméstico = house-elf; Dobby is the key house-elf of this book)", type: "noun", freq: 29 },
  { sp: "muchacho", en: "boy / lad / youngster (informal address)", type: "noun", freq: 29 },
  { sp: "frente", en: "forehead / front (la cicatriz en la frente = the scar on Harry's forehead)", type: "noun", freq: 29 },
  { sp: "único", en: "unique / only / sole (el único = the only one)", type: "adj", freq: 29 },
  { sp: "final", en: "end / finale / ending (al final = in the end; final del curso = end of term)", type: "noun", freq: 29 },
  { sp: "dejar", en: "to leave / to let / to allow (déjame en paz = leave me alone; dejar caer = to drop)", type: "verb", freq: 29 },
  { sp: "paso", en: "step / pace / passage (dar un paso = to take a step; abrir paso = to make way)", type: "noun", freq: 29 },
  { sp: "camino", en: "path / road / way (en el camino = on the way; allanar el camino = to pave the way)", type: "noun", freq: 29 },
  { sp: "piedra", en: "stone (la piedra filosofal = the Philosopher's Stone, previous book)", type: "noun", freq: 28 },
  { sp: "mañana", en: "morning / tomorrow (mañana por la mañana = tomorrow morning)", type: "noun", freq: 28 },
  { sp: "vida", en: "life (en vida = while alive; salvar la vida = to save one's life)", type: "noun", freq: 28 },
  { sp: "punto", en: "point / dot / moment (estar a punto de = to be about to)", type: "noun", freq: 28 },
  { sp: "entrar", en: "to enter / to go in (entrar en la cámara = to enter the chamber)", type: "verb", freq: 28 },
  { sp: "expresión", en: "expression / look (expresión de sorpresa = expression of surprise)", type: "noun", freq: 28 },
  { sp: "monstruo", en: "monster / beast (el monstruo de la Cámara = the monster of the Chamber)", type: "noun", freq: 28 },
  { sp: "golpe", en: "blow / hit / knock (de un golpe = in one blow; golpe seco = sharp knock)", type: "noun", freq: 27 },
  { sp: "viejo", en: "old / elderly / ancient (viejo mago = old wizard)", type: "adj", freq: 27 },
  { sp: "despacho", en: "office / study (el despacho de Dumbledore = Dumbledore's office)", type: "noun", freq: 27 },
  { sp: "vuelta", en: "turn / return / lap (dar la vuelta = to turn around; de vuelta = back)", type: "noun", freq: 26 },
  { sp: "comedor", en: "dining hall (el Gran Comedor = the Great Hall at Hogwarts)", type: "noun", freq: 26 },
  { sp: "pared", en: "wall (el mensaje en la pared = the message on the wall — key plot clue)", type: "noun", freq: 26 },
  { sp: "cuerpo", en: "body / corpus (cuerpo petrificado = petrified body)", type: "noun", freq: 26 },
  { sp: "campo", en: "field / pitch (campo de Quidditch = Quidditch pitch)", type: "noun", freq: 26 },
  { sp: "resto", en: "rest / remainder (el resto de los alumnos = the rest of the students)", type: "noun", freq: 25 },
  { sp: "negro", en: "black (magia negra = black magic; artes oscuras = Dark Arts)", type: "adj", freq: 25 },
  { sp: "pequeño", en: "small / little / young (pequeño elfo = little elf)", type: "adj", freq: 25 },
  { sp: "corazón", en: "heart (con el corazón en un puño = with heart in mouth — gripped by fear)", type: "noun", freq: 25 },
  { sp: "común", en: "common / shared (sala común = common room; sentido común = common sense)", type: "adj", freq: 25 },
  { sp: "tono", en: "tone / shade / pitch (en tono serio = in a serious tone)", type: "noun", freq: 25 },
  { sp: "habitación", en: "room / bedroom (la habitación de Harry = Harry's room at the Dursleys')", type: "noun", freq: 24 },
  { sp: "tía", en: "aunt (tía Petunia = Aunt Petunia)", type: "noun", freq: 24 },
  { sp: "grito", en: "shout / scream / cry (lanzar un grito = to let out a scream)", type: "noun", freq: 24 },
  { sp: "alto", en: "tall / high / loud (en voz alta = aloud; de alto = tall)", type: "adj", freq: 24 },
  { sp: "enfermería", en: "infirmary / hospital wing (run by Madam Pomfrey at Hogwarts)", type: "noun", freq: 24 },
  { sp: "bosque", en: "forest / woods (el Bosque Prohibido = the Forbidden Forest)", type: "noun", freq: 23 },
  { sp: "alrededor", en: "around / surrounding (a su alrededor = around him; mirar alrededor = to look around)", type: "adv", freq: 23 },
  { sp: "lista", en: "list / ready / clever (lista de útiles = supplies list; ¡está lista! = she's ready!)", type: "noun", freq: 23 },
  { sp: "explicar", en: "to explain (explicar la situación = to explain the situation)", type: "verb", freq: 23 },
  { sp: "director", en: "headmaster / principal (el director Dumbledore = Headmaster Dumbledore)", type: "noun", freq: 23 },
  { sp: "cerca", en: "near / close (cerca de = near / close to; de cerca = up close)", type: "adv", freq: 23 },
  { sp: "largo", en: "long / lengthy (a lo largo de = along; largo rato = a long while)", type: "adj", freq: 23 },
  { sp: "bastante", en: "quite / enough / rather (bastante bien = quite well; ya es bastante = that's enough)", type: "adv", freq: 23 },
  { sp: "chimenea", en: "fireplace (la red Flu = Floo Network, used via chimenea to travel between wizarding homes)", type: "noun", freq: 23 },
  { sp: "caso", en: "case / matter (en todo caso = in any case; hacer caso = to pay attention / to heed)", type: "noun", freq: 23 },
  { sp: "escoba", en: "broomstick (escoba voladora = flying broomstick; Harry's Nimbus 2000)", type: "noun", freq: 22 },
  { sp: "carta", en: "letter (carta de Hogwarts = Hogwarts acceptance letter; carta de Dobby)", type: "noun", freq: 22 },
  { sp: "capa", en: "cloak / cape / layer (capa de invisibilidad = invisibility cloak)", type: "noun", freq: 22 },
  { sp: "fuerza", en: "strength / force (con todas sus fuerzas = with all one's strength)", type: "noun", freq: 22 },
  { sp: "oscuro", en: "dark / obscure (artes oscuras = Dark Arts; el señor oscuro = the Dark Lord)", type: "adj", freq: 22 },
  { sp: "historia", en: "history / story (Historia de la Magia = History of Magic — a Hogwarts subject)", type: "noun", freq: 22 },
  { sp: "caldero", en: "cauldron (caldero de pociones = potion cauldron — essential Potions equipment)", type: "noun", freq: 21 },
  { sp: "pensar", en: "to think / to consider / to intend (pensar en = to think about)", type: "verb", freq: 21 },
  { sp: "oscuridad", en: "darkness / the dark (en la oscuridad = in the dark)", type: "noun", freq: 21 },
  { sp: "rojo", en: "red (pelo rojo = red hair — the Weasley family trademark)", type: "adj", freq: 21 },
  { sp: "dedo", en: "finger / toe (señalar con el dedo = to point a finger at)", type: "noun", freq: 21 },
  { sp: "despacio", en: "slowly / gently (hablar despacio = to speak slowly)", type: "adv", freq: 21 },
  { sp: "retrete", en: "toilet / bathroom (el retrete de Myrtle = Myrtle's bathroom — entrance to the Chamber)", type: "noun", freq: 21 },
  { sp: "lechuza", en: "owl (lechuza mensajera = messenger owl; Hedwig is Harry's snowy owl)", type: "noun", freq: 20 },
  { sp: "parte", en: "part / side / place (por parte de = on behalf of; en ninguna parte = nowhere)", type: "noun", freq: 20 },
  { sp: "silla", en: "chair (silla del profesor = teacher's chair)", type: "noun", freq: 20 },
  { sp: "tamaño", en: "size / magnitude (del tamaño de = the size of)", type: "noun", freq: 20 },
  { sp: "hombre", en: "man (hombre invisible = invisible man)", type: "noun", freq: 20 },
  { sp: "aspecto", en: "appearance / aspect / look (tener buen aspecto = to look well)", type: "noun", freq: 20 },
  { sp: "siguiente", en: "following / next (al día siguiente = the next day)", type: "adj", freq: 20 },
  { sp: "volar", en: "to fly (volar en escoba = to fly on a broomstick)", type: "verb", freq: 20 },
  { sp: "encontrar", en: "to find / to meet / to encounter (encontrar la cámara = to find the chamber)", type: "verb", freq: 20 },
  { sp: "desaparecer", en: "to disappear / to vanish (desaparecer sin dejar rastro = to vanish without a trace)", type: "verb", freq: 20 },
  { sp: "petrificar", en: "to petrify / to turn to stone (the Basilisk's indirect gaze petrifies its victims)", type: "verb", freq: 20 },
  { sp: "extraño", en: "strange / odd / foreign (un sonido extraño = a strange sound)", type: "adj", freq: 19 },
  { sp: "susurrar", en: "to whisper / to murmur (susurrar en la oscuridad = to whisper in the dark)", type: "verb", freq: 19 },
  { sp: "sujetar", en: "to hold / to grip / to fasten (sujetar la varita = to grip the wand)", type: "verb", freq: 19 },
  { sp: "espejo", en: "mirror (el espejo de Oesed = the Mirror of Erised, previous book)", type: "noun", freq: 19 },
  { sp: "columna", en: "column / pillar (columnas de piedra = stone columns in the Chamber of Secrets)", type: "noun", freq: 19 },
  { sp: "asustar", en: "to frighten / to scare (asustar a alguien = to scare someone)", type: "verb", freq: 18 },
  { sp: "lanzar", en: "to throw / to launch / to cast (lanzar un hechizo = to cast a spell)", type: "verb", freq: 18 },
  { sp: "frío", en: "cold (hace frío = it's cold; sangre fría = composure under pressure)", type: "adj", freq: 18 },
  { sp: "transformar", en: "to transform / to change form (the Polyjuice Potion transforms the drinker)", type: "verb", freq: 18 },
  { sp: "murmurar", en: "to murmur / to mutter (murmurar entre dientes = to mutter under one's breath)", type: "verb", freq: 18 },
  { sp: "acudir", en: "to come / to go / to turn to (acudir en ayuda = to come to the rescue)", type: "verb", freq: 18 },
  { sp: "enorme", en: "enormous / huge (una serpiente enorme = an enormous serpent)", type: "adj", freq: 18 },
  { sp: "peligro", en: "danger / peril (en peligro = in danger; peligro de muerte = mortal danger)", type: "noun", freq: 18 },
  { sp: "hechizo", en: "spell / charm / hex (lanzar un hechizo = to cast a spell)", type: "noun", freq: 18 },
  { sp: "tratar", en: "to treat / to try / to deal with (tratar de = to try to)", type: "verb", freq: 17 },
  { sp: "avanzar", en: "to advance / to move forward / to progress", type: "verb", freq: 17 },
  { sp: "nota", en: "note / grade (una nota en el escritorio = a note on the desk)", type: "noun", freq: 17 },
  { sp: "brillar", en: "to shine / to gleam / to glow (los ojos brillaban = the eyes gleamed)", type: "verb", freq: 17 },
  { sp: "pálido", en: "pale / pallid (quedarse pálido = to go pale from shock or fear)", type: "adj", freq: 17 },
  { sp: "imagen", en: "image / picture / reflection (la imagen en el espejo = the image in the mirror)", type: "noun", freq: 17 },
  { sp: "acercarse", en: "to approach / to draw near / to come closer", type: "verb", freq: 17 },
  { sp: "aseo", en: "toilet / washroom (aseos = bathrooms — Myrtle haunts the girls' aseos)", type: "noun", freq: 24 },
  { sp: "inmediatamente", en: "immediately / at once", type: "adv", freq: 23 },
  { sp: "abajo", en: "below / down / downstairs (hacia abajo = downward; boca abajo = face down)", type: "adv", freq: 22 },
  { sp: "quizá", en: "perhaps / maybe (quizá sea = perhaps it is — triggers subjunctive at C1)", type: "adv", freq: 19 },
  { sp: "muerto", en: "dead / deceased (muerto de miedo = scared to death)", type: "adj", freq: 19 },
  { sp: "abrir", en: "to open (abrir la puerta = to open the door; abrir camino = to forge a path)", type: "verb", freq: 19 },
  { sp: "caer", en: "to fall / to drop (caer al suelo = to fall to the floor; dejar caer = to drop)", type: "verb", freq: 19 },
  { sp: "diente", en: "tooth / fang (dientes de serpiente = snake fangs — the Basilisk's weapon)", type: "noun", freq: 19 },
  { sp: "último", en: "last / final / latest (el último año = the final year; por último = lastly)", type: "adj", freq: 19 },
  { sp: "fuego", en: "fire (fuego mágico = magical fire; Fawkes renace del fuego = Fawkes reborn from fire)", type: "noun", freq: 19 },
  { sp: "cielo", en: "sky / heaven (el cielo estrellado = the starry sky — Hogwarts enchanted ceiling)", type: "noun", freq: 19 },
  { sp: "lleno", en: "full / filled (lleno de miedo = filled with fear; a pleno = in full)", type: "adj", freq: 19 },
  { sp: "agua", en: "water (agua lodosa = muddy water)", type: "noun", freq: 19 },
  { sp: "piel", en: "skin / hide / fur (ponérsele la piel de gallina = to get goosebumps)", type: "noun", freq: 19 },
  { sp: "querido", en: "dear / beloved (querido diario = dear diary — Riddle's diary entries)", type: "adj", freq: 19 },
  { sp: "jaula", en: "cage (la jaula de Hedwig = Hedwig's cage)", type: "noun", freq: 18 },
  { sp: "bruja", en: "witch (bruja malvada = wicked witch; female wizard)", type: "noun", freq: 18 },
  { sp: "sitio", en: "place / spot (en este sitio = in this place; hacer sitio = to make room)", type: "noun", freq: 18 },
  { sp: "sol", en: "sun (a pleno sol = in full sun; salir el sol = for the sun to rise)", type: "noun", freq: 18 },
  { sp: "algún", en: "some / any (algún mago = some wizard; algún día = someday)", type: "adj", freq: 18 },
  { sp: "fantasma", en: "ghost (los fantasmas de Hogwarts; Nearly Headless Nick is a fantasma)", type: "noun", freq: 18 },
  { sp: "lengua", en: "tongue / language (lengua de serpiente = snake tongue; Parseltongue)", type: "noun", freq: 18 },
  { sp: "trabajo", en: "work / job / task (trabajo de clase = class assignment; trabajo duro = hard work)", type: "noun", freq: 18 },
  { sp: "callejón", en: "alley (el Callejón Diagon = Diagon Alley; el Callejón Knockturn = Knockturn Alley)", type: "noun", freq: 18 },
  { sp: "hombro", en: "shoulder (encogerse de hombros = to shrug)", type: "noun", freq: 18 },
  { sp: "persona", en: "person / individual (una persona de confianza = a trusted person)", type: "noun", freq: 18 },
  { sp: "muro", en: "wall / barrier (muro de piedra = stone wall; muro de contención = retaining wall)", type: "noun", freq: 18 },
  { sp: "extremo", en: "end / extreme / tip (al otro extremo = at the other end; en casos extremos)", type: "noun", freq: 18 },
  { sp: "aula", en: "classroom / lecture hall (aula de transformaciones = Transfiguration classroom)", type: "noun", freq: 18 },
  { sp: "sucio", en: "dirty / filthy (sangre sucia = Mudblood — HP slur for Muggle-born wizard)", type: "adj", freq: 18 },
  { sp: "realmente", en: "really / truly / in reality (B2 intensifier)", type: "adv", freq: 18 },
  { sp: "amigo", en: "friend / mate (mi mejor amigo = my best friend)", type: "noun", freq: 17 },
  { sp: "pociones", en: "Potions (school subject; la clase de Pociones = Potions class — Snape's domain)", type: "noun", freq: 17 },
  { sp: "baúl", en: "trunk / chest (el baúl de Harry = Harry's school trunk)", type: "noun", freq: 17 },
  { sp: "verde", en: "green (los ojos verdes de Harry; la marca verde = the Dark Mark in the sky)", type: "adj", freq: 17 },
  { sp: "brillante", en: "brilliant / shining / gleaming (ojos brillantes = gleaming eyes)", type: "adj", freq: 17 },
  { sp: "supuesto", en: "supposed / assumed (por supuesto = of course — essential B2 fixed phrase)", type: "adj", freq: 17 },
  { sp: "armario", en: "wardrobe / cupboard (el armario debajo de la escalera = Harry's cupboard under the stairs)", type: "noun", freq: 17 },
  { sp: "vistazo", en: "glance / quick look (echar un vistazo = to have a quick look)", type: "noun", freq: 17 },
  { sp: "prefecto", en: "prefect (student monitor at Hogwarts; Percy Weasley is a prefecto)", type: "noun", freq: 17 },
  { sp: "madre", en: "mother / mum (madre de sangre pura = pure-blood mother)", type: "noun", freq: 17 },
  { sp: "coger", en: "to grab / to take / to catch (Spain: coger la varita = to grab the wand)", type: "verb", freq: 17 },
  { sp: "tinta", en: "ink (tinta invisible = invisible ink; Riddle's diary absorbs and releases tinta)", type: "noun", freq: 17 },
  { sp: "premio", en: "prize / award (Lockhart's many Premio awards line his office walls)", type: "noun", freq: 17 },
  { sp: "rápidamente", en: "quickly / rapidly (B2 adverb of manner)", type: "adv", freq: 17 },
  { sp: "seleccionador", en: "selector / sorting agent (Sombrero Seleccionador = Sorting Hat)", type: "noun", freq: 17 },
  { sp: "demás", en: "the rest / the others (los demás alumnos = the other students)", type: "adj", freq: 17 },
  { sp: "muerte", en: "death (la Orden de la Muerte = Death Eaters; pena de muerte = death penalty)", type: "noun", freq: 17 },
  { sp: "señorita", en: "Miss / young woman (señorita Granger = Miss Granger)", type: "noun", freq: 17 },
  { sp: "fiesta", en: "party / celebration (la fiesta de Casi Decapitado = Nearly Headless Nick's deathday party)", type: "noun", freq: 17 },
  { sp: "impresión", en: "impression / shock (dar buena impresión = to make a good impression)", type: "noun", freq: 16 },
  { sp: "cumpleaños", en: "birthday (el peor cumpleaños = the worst birthday — Chapter 1 title)", type: "noun", freq: 16 },
  { sp: "seguir", en: "to follow / to continue / to keep on (seguir adelante = to keep going)", type: "verb", freq: 16 },
  { sp: "salto", en: "jump / leap (dar un salto = to leap; pegar un salto = to give a start)", type: "noun", freq: 16 },
  { sp: "verano", en: "summer (las vacaciones de verano = summer holidays)", type: "noun", freq: 16 },
  { sp: "importante", en: "important / significant (lo más importante = the most important thing)", type: "adj", freq: 16 },
  { sp: "montón", en: "heap / pile / loads (un montón de = loads of — B2 colloquial intensifier)", type: "noun", freq: 16 },
  { sp: "pierna", en: "leg (las piernas temblorosas = trembling legs)", type: "noun", freq: 16 },
  { sp: "mitad", en: "half / midpoint (a mitad de camino = halfway; la mitad del curso = mid-term)", type: "noun", freq: 16 },
  { sp: "mamá", en: "mum / mom (informal; used by the Weasley children for Mrs Weasley)", type: "noun", freq: 16 },
  { sp: "cabo", en: "end / detail (al cabo de = after; llevar a cabo = to carry out; al fin y al cabo = after all)", type: "noun", freq: 16 },
  { sp: "defensa", en: "defence (Defensa Contra las Artes Oscuras = Defence Against the Dark Arts)", type: "noun", freq: 16 },
  { sp: "velocidad", en: "speed / velocity (a toda velocidad = at full speed)", type: "noun", freq: 16 },
  { sp: "entrada", en: "entrance / entry (la entrada de la cámara = the entrance to the chamber)", type: "noun", freq: 16 },
  { sp: "difícil", en: "difficult / hard / tricky (una situación difícil = a difficult situation)", type: "adj", freq: 16 },
  { sp: "vela", en: "candle (las velas flotantes del Gran Comedor = the floating candles of the Great Hall)", type: "noun", freq: 16 },
  { sp: "bolsa", en: "bag / purse / pouch (la bolsa de galeones = the bag of Galleons)", type: "noun", freq: 16 },
  { sp: "peor", en: "worse / worst (el peor cumpleaños = the worst birthday; de mal en peor = from bad to worse)", type: "adj", freq: 19 },
  { sp: "favor", en: "favour (por favor = please; a favor de = in favour of; pedir un favor = to ask a favour)", type: "noun", freq: 19 },
  { sp: "partido", en: "match / game / party (partido de Quidditch = Quidditch match)", type: "noun", freq: 19 },
  { sp: "pájaro", en: "bird (el pájaro de fuego = the firebird — Fawkes the phoenix)", type: "noun", freq: 19 },
  { sp: "arriba", en: "above / up / upstairs (hacia arriba = upward; de arriba abajo = from top to bottom)", type: "adv", freq: 17 },
  { sp: "suficiente", en: "enough / sufficient (ya es suficiente = that's enough; suficiente para = enough to)", type: "adj", freq: 15 },
  { sp: "cocina", en: "kitchen (la cocina de los Weasley = the Weasleys' kitchen at the Burrow)", type: "noun", freq: 15 },
  { sp: "furioso", en: "furious / enraged / livid (ponerse furioso = to become furious)", type: "adj", freq: 15 },
  { sp: "vacaciones", en: "holidays / vacation (vacaciones de verano = summer holidays)", type: "noun", freq: 15 },
  { sp: "torre", en: "tower (la Torre de Gryffindor = Gryffindor Tower; la Torre de Astronomía)", type: "noun", freq: 15 },
  { sp: "cabaña", en: "hut / cabin (la cabaña de Hagrid = Hagrid's hut on Hogwarts grounds)", type: "noun", freq: 15 },
  { sp: "cicatriz", en: "scar (la cicatriz en la frente de Harry = Harry's lightning-bolt scar)", type: "noun", freq: 15 },
  { sp: "exactamente", en: "exactly / precisely (eso es exactamente = that is exactly it)", type: "adv", freq: 15 },
  { sp: "comer", en: "to eat (comer en el Gran Comedor = to eat in the Great Hall)", type: "verb", freq: 15 },
  { sp: "famoso", en: "famous / renowned (Lockhart es famoso = Lockhart is famous — for fabricated deeds)", type: "adj", freq: 15 },
  { sp: "oreja", en: "ear (outer ear; aguzar las orejas = to prick up one's ears)", type: "noun", freq: 15 },
  { sp: "punta", en: "tip / point / end (la punta de la varita = the tip of the wand)", type: "noun", freq: 15 },
  { sp: "piso", en: "floor / storey / flat (el primer piso = the first floor; vivir en un piso = to live in a flat)", type: "noun", freq: 15 },
  { sp: "poder", en: "power / ability; to be able to (el poder del basilisco = the basilisk's power)", type: "noun", freq: 15 },
  { sp: "fénix", en: "phoenix (Fawkes, Dumbledore's fénix — loyal, tears heal, reborn from ashes)", type: "noun", freq: 15 },
  { sp: "espada", en: "sword (la espada de Godric Gryffindor = Godric Gryffindor's sword — key plot weapon)", type: "noun", freq: 15 },
  { sp: "susurro", en: "whisper / murmur (un susurro en la pared = a whisper in the wall — the Basilisk)", type: "noun", freq: 15 },
  { sp: "ocupado", en: "busy / occupied (estar ocupado = to be busy; el baño está ocupado = the bathroom is occupied)", type: "adj", freq: 15 },
  { sp: "oscurecer", en: "to darken / to grow dark (el cielo empezó a oscurecer = the sky began to darken)", type: "verb", freq: 15 },
];

export type AppSeedCard = {
  front: string;
  back: string;
  tags: string[];
  extra: {
    type: PartOfSpeech;
    freq: number;
    source: "hp-chamber-of-secrets";
  };
};

const dedupeKey = (record: SeedCardRecord) =>
  `${record.sp.trim().toLowerCase()}|${record.en.trim().toLowerCase()}|${record.type}`;

export const FORMATTED_SEED_CARDS: AppSeedCard[] = SEED_CARD_DECK.reduce<AppSeedCard[]>((cards, record) => {
  const normalizedFront = record.sp.trim();
  const normalizedBack = record.en.trim();

  if (!normalizedFront || !normalizedBack) {
    return cards;
  }

  const key = dedupeKey(record);
  const alreadyIncluded = cards.some(
    (card) =>
      `${card.front.trim().toLowerCase()}|${card.back.trim().toLowerCase()}|${card.extra.type}` === key,
  );

  if (alreadyIncluded) {
    return cards;
  }

  cards.push({
    front: normalizedFront,
    back: normalizedBack,
    tags: [record.type, "hp-chamber-of-secrets", `freq-${Math.max(1, Math.round(record.freq / 10) * 10)}`],
    extra: {
      type: record.type,
      freq: record.freq,
      source: "hp-chamber-of-secrets",
    },
  });

  return cards;
}, []);

export const TOTAL_SOURCE_CARDS = SEED_CARD_DECK.length;
export const TOTAL_FORMATTED_CARDS = FORMATTED_SEED_CARDS.length;