export type SeedCardRecord = {
  sp: string;
  en: string;
};

export const SEED_CARD_DECK: SeedCardRecord[] = [
  { sp: "decir", en: "to say / to tell" },
  { sp: "preguntar", en: "to ask / to question" },
  { sp: "gritar", en: "to shout / to scream" },
  { sp: "mirar", en: "to look at / to watch" },
  { sp: "abrir", en: "to open" },
  { sp: "levantar", en: "to raise / to lift" },
  { sp: "coger", en: "to grab / to take (Spain)" },
  { sp: "responder", en: "to respond / to reply" },
  { sp: "susurrar", en: "to whisper" },
  { sp: "añadir", en: "to add / to say furthermore" },
  { sp: "contestar", en: "to answer / to reply" },
  { sp: "sacar", en: "to take out / to pull out" },
  { sp: "dejar", en: "to let / to leave behind" },
  { sp: "llegar", en: "to arrive / to reach" },
  { sp: "acercar", en: "to approach / to bring closer" },
  { sp: "volver", en: "to return / to go back" },
  { sp: "entrar", en: "to enter / to go in" },
  { sp: "correr", en: "to run" },
  { sp: "hablar", en: "to speak / to talk" },
  { sp: "escuchar", en: "to listen / to hear" },
  { sp: "intentar", en: "to try / to attempt" },
  { sp: "parecer", en: "to seem / to appear" },
  { sp: "recordar", en: "to remember / to remind" },
  { sp: "caer", en: "to fall" },
  { sp: "empujar", en: "to push / to shove" },
  { sp: "murmurar", en: "to murmur / to mutter" },
  { sp: "desaparecer", en: "to disappear (wizard context: vanish)" },
  { sp: "transformar", en: "to transform / to change form (spell)" },
  { sp: "atravesar", en: "to cross / to pass through" },
  { sp: "lanzar", en: "to throw / to launch / to cast (a spell)" },

  // NOUNS
  { sp: "varita", en: "wand (wizarding tool for casting spells)" },
  { sp: "cámara", en: "chamber / camera" },
  { sp: "magia", en: "magic [mágico]" },
  { sp: "puerta", en: "door / gate [abrir]" },
  { sp: "ojo", en: "eye [mirar]" },
  { sp: "cabeza", en: "head / mind [pensar]" },
  { sp: "mano", en: "hand [coger]" },
  { sp: "voz", en: "voice [hablar]" },
  { sp: "cara", en: "face / expression [mirar]" },
  { sp: "suelo", en: "floor / ground" },
  { sp: "castillo", en: "castle (Hogwarts setting)" },
  { sp: "sangre", en: "blood (key HP theme: blood purity)" },
  { sp: "serpiente", en: "serpent / snake [Slytherin symbol]" },
  { sp: "sombrero", en: "hat (the Sorting Hat in HP context)" },
  { sp: "araña", en: "spider [Aragog's species]" },
  { sp: "elfo", en: "elf (house-elf: wizarding servant)" },
  { sp: "mago", en: "wizard / sorcerer [magia]" },
  { sp: "poción", en: "potion (brewed magical liquid)" },
  { sp: "heredero", en: "heir / inheritor [heredar]" },
  { sp: "basilisco", en: "basilisk (legendary lethal serpent)" },
  { sp: "corredor", en: "corridor / hallway [castle passages]" },
  { sp: "diario", en: "diary / daily [Riddle's diary, key plot item]" },
  { sp: "secreto", en: "secret [Chamber of Secrets]" },
  { sp: "mundo", en: "world [el mundo mágico = wizarding world]" },
  { sp: "palaba", en: "word [palabras mágicas = magic words]" },
  { sp: "silencio", en: "silence / quiet [silenciar]" },
  { sp: "equipo", en: "team / equipment [Quidditch teams]" },
  { sp: "ventana", en: "window [abrir la ventana]" },
  { sp: "escalera", en: "stairs / staircase [castle stairs]" },
  { sp: "dormitorio", en: "dormitory / bedroom [Gryffindor dorm]" },
  { sp: "gafa", en: "glasses / spectacles [Harry's trademark]" },
  { sp: "nariz", en: "nose [nariz aguileña = hooked nose]" },
  { sp: "brazo", en: "arm [el brazo roto = broken arm]" },
  { sp: "pie", en: "foot / feet (standing point) [de pie = standing]" },
  { sp: "techo", en: "ceiling / roof [enchanted ceiling at Hogwarts]" },
  { sp: "rostro", en: "face / countenance (literary, more formal than cara)" },
  { sp: "multitud", en: "crowd / multitude [multitudinario]" },
  { sp: "instante", en: "instant / moment [al instante = instantly]" },
  { sp: "sonrisa", en: "smile [sonreír]" },
  { sp: "mirada", en: "gaze / look / glance [mirar]" },
  { sp: "túnica", en: "robe / tunic (wizarding garment)" },
  { sp: "curso", en: "school year / course [second year at Hogwarts]" },
  { sp: "ruido", en: "noise / sound [hacer ruido]" },
  { sp: "camino", en: "path / road / way [allanar el camino]" },
  { sp: "piedra", en: "stone [Philosopher's Stone, prev. book]" },
  { sp: "noche", en: "night [de noche = at night]" },
  { sp: "vida", en: "life [en vida = alive]" },
  { sp: "nombre", en: "name [el-que-no-debe-ser-nombrado]" },
  { sp: "idea", en: "idea / plan [buena idea]" },
  { sp: "manera", en: "manner / way [de ninguna manera = no way]" },
  { sp: "lugar", en: "place / location [en su lugar = instead]" },
  { sp: "gente", en: "people / folk [la gente del colegio]" },
  { sp: "familia", en: "family [familia Weasley = the Weasley family]" },
  { sp: "libro", en: "book [libros de texto = textbooks]" },
  { sp: "alumno", en: "student / pupil [alumnos de Hogwarts]" },
  { sp: "tiempo", en: "time / weather [con el tiempo = in time]" },
  { sp: "colegio", en: "school (here: Hogwarts) [colegial]" },
  { sp: "padre", en: "father / parent [padre mágico]" },
  { sp: "pelo", en: "hair [pelo revuelto = messy hair like Harry's]" },
  { sp: "boca", en: "mouth [boca abierta = open-mouthed]" },
  { sp: "prisa", en: "hurry / haste [darse prisa = to hurry]" },
  { sp: "frente", en: "forehead / front [la cicatriz en la frente]" },
  { sp: "muchacho", en: "boy / lad / youngster" },
  { sp: "aire", en: "air / atmosphere [en el aire = in the air]" },
  { sp: "minuto", en: "minute [en pocos minutos = in a few minutes]" },
  { sp: "tarde", en: "afternoon / late (time adverb) [por la tarde]" },
  { sp: "mañana", en: "morning / tomorrow [mañana por la mañana]" },
  { sp: "punto", en: "point / dot / period [en ese punto = at that point]" },
  { sp: "cama", en: "bed [irse a la cama = to go to bed]" },
  { sp: "sala", en: "common room / hall / lounge [sala común]" },
  { sp: "mesa", en: "table / desk [mesa del comedor]" },
  { sp: "forma", en: "form / shape / way [de alguna forma]" },
  { sp: "clase", en: "class / classroom / kind [clase de pociones]" },
  { sp: "muggle", en: "Muggle (non-magical person, HP term)" },
  { sp: "coche", en: "car (the flying Ford Anglia)" },
  { sp: "casa", en: "house (also Hogwarts houses) [Gryffindor]" },

  // ADJECTIVES
  { sp: "mágico", en: "magical / magic [magia]" },
  { sp: "grande", en: "big / great / grand [grandioso]" },
  { sp: "seguro", en: "safe / sure / certain [asegurar]" },
  { sp: "fuerte", en: "strong / loud / hard [fortalecer]" },
  { sp: "extraño", en: "strange / foreign / odd [extrañar]" },
  { sp: "oscuro", en: "dark / obscure [oscurecer] (dark arts context)" },
  { sp: "pequeño", en: "small / little / young [pequeñez]" },
  { sp: "enorme", en: "enormous / huge [enormidad]" },
  { sp: "asustado", en: "scared / frightened [asustar]" },
  { sp: "pálido", en: "pale / pallid [palidecer]" },
  { sp: "único", en: "unique / only / sole [unicidad]" },
  { sp: "horrible", en: "horrible / dreadful / awful" },
  { sp: "segundo", en: "second (ordinal) [segundo año = second year]" },
  { sp: "primero", en: "first / primary [primera vez = first time]" },
  { sp: "completo", en: "complete / entire / full [completamente]" },
  { sp: "negro", en: "black [el gato negro de la señora Norris]" },
  { sp: "blanco", en: "white / blank [página en blanco]" },
  { sp: "plateado", en: "silver / silvery [platear] (Nearly Headless Nick)" },
  { sp: "frío", en: "cold / cool [enfriar] (cold dungeons of Slytherin)" },
  { sp: "brillante", en: "brilliant / shining / glowing [brillar]" },
  { sp: "tembloroso", en: "trembling / shaky [temblar]" },
  { sp: "ansioso", en: "anxious / eager / keen [ansiar]" },
  { sp: "nervioso", en: "nervous / anxious [nerviosismo]" },
  { sp: "silencioso", en: "silent / quiet [silencio]" },
  { sp: "doloroso", en: "painful / distressing [doler]" },
  { sp: "encantado", en: "enchanted / delighted (lit: under a spell) [encantar]" },
  { sp: "decapitado", en: "beheaded / decapitated [decapitar] (Nearly-Headless Nick)" },
  { sp: "plateado", en: "silver-colored / silvery [plata]" },
  { sp: "poderoso", en: "powerful / mighty [poder]" },
  { sp: "verdadero", en: "true / real / genuine [verdad]" },
  { sp: "malvado", en: "wicked / evil / villainous [maldad]" },
  { sp: "muggle", en: "Muggle (non-magical — also used as adj)" },
  { sp: "famoso", en: "famous / renowned [fama] (Lockhart is famoso)" },
  { sp: "inmóvil", en: "motionless / still / immobile [moverse]" },
  { sp: "petrificado", en: "petrified / frozen in fear (lit: turned to stone) [petrificar]" },
  { sp: "grande", en: "big / great / large (gran before noun = great)" },
  { sp: "tío", en: "uncle (tío Vernon = Uncle Vernon; colloquial: guy/dude)" },
  { sp: "oído", en: "ear / inner hearing (tocar de oído = to play by ear)" },
  { sp: "familia", en: "family" },
  { sp: "silencio", en: "silence / quiet (en silencio = in silence)" },
  { sp: "curso", en: "school year / course (segundo curso = second year)" },
  { sp: "salir", en: "to leave / to go out / to exit" },
  { sp: "pelo", en: "hair (pelo revuelto = messy hair, like Harry's)" },
  { sp: "mago", en: "wizard / sorcerer / magician" },
  { sp: "alumno", en: "student / pupil (alumnos de Hogwarts = Hogwarts students)" },
  { sp: "araña", en: "spider (Aragog and his colony of Acromantulas)" },
  { sp: "muggle", en: "Muggle (non-magical person — HP-specific term)" },
  { sp: "ruido", en: "noise / sound (hacer ruido = to make noise)" },
  { sp: "brazo", en: "arm (el brazo roto = the broken arm — Lockhart's blunder)" },
  { sp: "volver", en: "to return / to come back / to go back" },
  { sp: "túnica", en: "robe / tunic (the standard wizarding garment)" },
  { sp: "corredor", en: "corridor / hallway / passage (castle corridors)" },
  { sp: "año", en: "year (este año = this year; años = years)" },
  { sp: "mundo", en: "world (el mundo mágico = the wizarding world)" },
  { sp: "forma", en: "form / shape / way (de esta forma = in this way)" },
  { sp: "sonrisa", en: "smile (una amplia sonrisa = a broad smile)" },
  { sp: "hora", en: "hour / time of day (¿qué hora es? = what time is it?)" },
  { sp: "palabra", en: "word (palabras mágicas = magic words)" },
  { sp: "equipo", en: "team / equipment (equipo de Quidditch = Quidditch team)" },
  { sp: "instante", en: "instant / moment (al instante = instantly)" },
  { sp: "ventana", en: "window" },
  { sp: "pasar", en: "to pass / to happen / to spend time (¿qué pasa? = what's happening?)" },
  { sp: "correr", en: "to run / to rush" },
  { sp: "fuerte", en: "strong / loud / hard (un golpe fuerte = a hard blow)" },
  { sp: "decapitado", en: "beheaded / decapitated (Nearly Headless Nick's defining condition)" },
  { sp: "nombre", en: "name (el-que-no-debe-ser-nombrado = He-Who-Must-Not-Be-Named)" },
  { sp: "pie", en: "foot (de pie = standing up; a pie = on foot)" },
  { sp: "cuidado", en: "care / caution (¡ten cuidado! = be careful!)" },
  { sp: "bludger", en: "Bludger (enchanted iron ball used in Quidditch to knock players off brooms)" },
  { sp: "rostro", en: "face / countenance (literary; more formal than cara)" },
  { sp: "poción", en: "potion (a brewed magical liquid; clase de Pociones = Potions class)" },
  { sp: "dar", en: "to give / to strike / to yield (dar un paso = to take a step)" },
  { sp: "techo", en: "ceiling / roof (el techo encantado del Gran Comedor = the enchanted ceiling)" },
  { sp: "escalera", en: "stairs / staircase (the moving staircases of Hogwarts)" },
  { sp: "idea", en: "idea / plan (buena idea = good idea)" },
  { sp: "minuto", en: "minute (en pocos minutos = in a few minutes)" },
  { sp: "primero", en: "first / primary (por primera vez = for the first time)" },
  { sp: "heredero", en: "heir / inheritor (el heredero de Slytherin = the Heir of Slytherin)" },
  { sp: "basilisco", en: "basilisk (the monstrous serpent living in the Chamber of Secrets)" },
  { sp: "nariz", en: "nose (nariz aguileña = hooked nose, like Snape's)" },
  { sp: "multitud", en: "crowd / multitude" },
  { sp: "seguro", en: "safe / sure / certain (estar seguro = to be sure)" },
  { sp: "tarde", en: "afternoon / late (por la tarde = in the afternoon)" },
  { sp: "manera", en: "manner / way (de ninguna manera = no way; in no way)" },
  { sp: "llegar", en: "to arrive / to reach (llegar a tiempo = to arrive on time)" },

  // ── BATCH 3 (words 101–200 by corpus frequency, normalized) ──
  { sp: "ningún", en: "no / none / not any (ningún mago = no wizard)" },
  { sp: "embargo", en: "sin embargo = however / nevertheless (B2 discourse connector)" },
  { sp: "atrás", en: "behind / back / backwards (echar atrás = to back away)" },
  { sp: "fin", en: "end / purpose (al fin = at last; por fin = finally; a fin de = in order to)" },
  { sp: "medio", en: "middle / half / means (en medio de = in the middle of; medio dormido = half asleep)" },
  { sp: "oír", en: "to hear (¿oyes eso? = do you hear that? — Harry hears the Basilisk)" },
  { sp: "dormitorio", en: "dormitory / bedroom (dormitorio de Gryffindor = Gryffindor dormitory)" },
  { sp: "repente", en: "de repente = suddenly / all of a sudden (B2 adverbial phrase)" },
  { sp: "prisa", en: "hurry / haste (darse prisa = to hurry; tener prisa = to be in a hurry)" },
  { sp: "elfo", en: "elf (elfo doméstico = house-elf; Dobby is the key house-elf of this book)" },
  { sp: "muchacho", en: "boy / lad / youngster (informal address)" },
  { sp: "frente", en: "forehead / front (la cicatriz en la frente = the scar on Harry's forehead)" },
  { sp: "único", en: "unique / only / sole (el único = the only one)" },
  { sp: "final", en: "end / finale / ending (al final = in the end; final del curso = end of term)" },
  { sp: "dejar", en: "to leave / to let / to allow (déjame en paz = leave me alone; dejar caer = to drop)" },
  { sp: "paso", en: "step / pace / passage (dar un paso = to take a step; abrir paso = to make way)" },
  { sp: "camino", en: "path / road / way (en el camino = on the way; allanar el camino = to pave the way)" },
  { sp: "piedra", en: "stone (la piedra filosofal = the Philosopher's Stone, previous book)" },
  { sp: "mañana", en: "morning / tomorrow (mañana por la mañana = tomorrow morning)" },
  { sp: "vida", en: "life (en vida = while alive; salvar la vida = to save one's life)" },
  { sp: "punto", en: "point / dot / moment (estar a punto de = to be about to)" },
  { sp: "entrar", en: "to enter / to go in (entrar en la cámara = to enter the chamber)" },
  { sp: "expresión", en: "expression / look (expresión de sorpresa = expression of surprise)" },
  { sp: "monstruo", en: "monster / beast (el monstruo de la Cámara = the monster of the Chamber)" },
  { sp: "golpe", en: "blow / hit / knock (de un golpe = in one blow; golpe seco = sharp knock)" },
  { sp: "viejo", en: "old / elderly / ancient (viejo mago = old wizard)" },
  { sp: "despacho", en: "office / study (el despacho de Dumbledore = Dumbledore's office)" },
  { sp: "vuelta", en: "turn / return / lap (dar la vuelta = to turn around; de vuelta = back)" },
  { sp: "comedor", en: "dining hall (el Gran Comedor = the Great Hall at Hogwarts)" },
  { sp: "pared", en: "wall (el mensaje en la pared = the message on the wall — key plot clue)" },
  { sp: "cuerpo", en: "body / corpus (cuerpo petrificado = petrified body)" },
  { sp: "campo", en: "field / pitch (campo de Quidditch = Quidditch pitch)" },
  { sp: "resto", en: "rest / remainder (el resto de los alumnos = the rest of the students)" },
  { sp: "negro", en: "black (magia negra = black magic; artes oscuras = Dark Arts)" },
  { sp: "pequeño", en: "small / little / young (pequeño elfo = little elf)" },
  { sp: "corazón", en: "heart (con el corazón en un puño = with heart in mouth — gripped by fear)" },
  { sp: "común", en: "common / shared (sala común = common room; sentido común = common sense)" },
  { sp: "tono", en: "tone / shade / pitch (en tono serio = in a serious tone)" },
  { sp: "habitación", en: "room / bedroom (la habitación de Harry = Harry's room at the Dursleys')" },
  { sp: "tía", en: "aunt (tía Petunia = Aunt Petunia)" },
  { sp: "grito", en: "shout / scream / cry (lanzar un grito = to let out a scream)" },
  { sp: "alto", en: "tall / high / loud (en voz alta = aloud; de alto = tall)" },
  { sp: "enfermería", en: "infirmary / hospital wing (run by Madam Pomfrey at Hogwarts)" },
  { sp: "bosque", en: "forest / woods (el Bosque Prohibido = the Forbidden Forest)" },
  { sp: "alrededor", en: "around / surrounding (a su alrededor = around him; mirar alrededor = to look around)" },
  { sp: "lista", en: "list / ready / clever (lista de útiles = supplies list; ¡está lista! = she's ready!)" },
  { sp: "explicar", en: "to explain (explicar la situación = to explain the situation)" },
  { sp: "director", en: "headmaster / principal (el director Dumbledore = Headmaster Dumbledore)" },
  { sp: "cerca", en: "near / close (cerca de = near / close to; de cerca = up close)" },
  { sp: "largo", en: "long / lengthy (a lo largo de = along; largo rato = a long while)" },
  { sp: "bastante", en: "quite / enough / rather (bastante bien = quite well; ya es bastante = that's enough)" },
  { sp: "chimenea", en: "fireplace (la red Flu = Floo Network, used via chimenea to travel between wizarding homes)" },
  { sp: "caso", en: "case / matter (en todo caso = in any case; hacer caso = to pay attention / to heed)" },
  { sp: "escoba", en: "broomstick (escoba voladora = flying broomstick; Harry's Nimbus 2000)" },
  { sp: "carta", en: "letter (carta de Hogwarts = Hogwarts acceptance letter; carta de Dobby)" },
  { sp: "capa", en: "cloak / cape / layer (capa de invisibilidad = invisibility cloak)" },
  { sp: "fuerza", en: "strength / force (con todas sus fuerzas = with all one's strength)" },
  { sp: "oscuro", en: "dark / obscure (artes oscuras = Dark Arts; el señor oscuro = the Dark Lord)" },
  { sp: "historia", en: "history / story (Historia de la Magia = History of Magic — a Hogwarts subject)" },
  { sp: "caldero", en: "cauldron (caldero de pociones = potion cauldron — essential Potions equipment)" },
  { sp: "pensar", en: "to think / to consider / to intend (pensar en = to think about)" },
  { sp: "oscuridad", en: "darkness / the dark (en la oscuridad = in the dark)" },
  { sp: "rojo", en: "red (pelo rojo = red hair — the Weasley family trademark)" },
  { sp: "dedo", en: "finger / toe (señalar con el dedo = to point a finger at)" },
  { sp: "despacio", en: "slowly / gently (hablar despacio = to speak slowly)" },
  { sp: "retrete", en: "toilet / bathroom (el retrete de Myrtle = Myrtle's bathroom — entrance to the Chamber)" },
  { sp: "lechuza", en: "owl (lechuza mensajera = messenger owl; Hedwig is Harry's snowy owl)" },
  { sp: "parte", en: "part / side / place (por parte de = on behalf of; en ninguna parte = nowhere)" },
  { sp: "silla", en: "chair (silla del profesor = teacher's chair)" },
  { sp: "tamaño", en: "size / magnitude (del tamaño de = the size of)" },
  { sp: "hombre", en: "man (hombre invisible = invisible man)" },
  { sp: "aspecto", en: "appearance / aspect / look (tener buen aspecto = to look well)" },
  { sp: "siguiente", en: "following / next (al día siguiente = the next day)" },
  { sp: "volar", en: "to fly (volar en escoba = to fly on a broomstick)" },
  { sp: "encontrar", en: "to find / to meet / to encounter (encontrar la cámara = to find the chamber)" },
  { sp: "desaparecer", en: "to disappear / to vanish (desaparecer sin dejar rastro = to vanish without a trace)" },
  { sp: "petrificar", en: "to petrify / to turn to stone (the Basilisk's indirect gaze petrifies its victims)" },
  { sp: "extraño", en: "strange / odd / foreign (un sonido extraño = a strange sound)" },
  { sp: "susurrar", en: "to whisper / to murmur (susurrar en la oscuridad = to whisper in the dark)" },
  { sp: "sujetar", en: "to hold / to grip / to fasten (sujetar la varita = to grip the wand)" },
  { sp: "espejo", en: "mirror (el espejo de Oesed = the Mirror of Erised, previous book)" },
  { sp: "columna", en: "column / pillar (columnas de piedra = stone columns in the Chamber of Secrets)" },
  { sp: "asustar", en: "to frighten / to scare (asustar a alguien = to scare someone)" },
  { sp: "lanzar", en: "to throw / to launch / to cast (lanzar un hechizo = to cast a spell)" },
  { sp: "frío", en: "cold (hace frío = it's cold; sangre fría = composure under pressure)" },
  { sp: "transformar", en: "to transform / to change form (the Polyjuice Potion transforms the drinker)" },
  { sp: "murmurar", en: "to murmur / to mutter (murmurar entre dientes = to mutter under one's breath)" },
  { sp: "acudir", en: "to come / to go / to turn to (acudir en ayuda = to come to the rescue)" },
  { sp: "enorme", en: "enormous / huge (una serpiente enorme = an enormous serpent)" },
  { sp: "peligro", en: "danger / peril (en peligro = in danger; peligro de muerte = mortal danger)" },
  { sp: "hechizo", en: "spell / charm / hex (lanzar un hechizo = to cast a spell)" },
  { sp: "tratar", en: "to treat / to try / to deal with (tratar de = to try to)" },
  { sp: "avanzar", en: "to advance / to move forward / to progress" },
  { sp: "nota", en: "note / grade (una nota en el escritorio = a note on the desk)" },
  { sp: "brillar", en: "to shine / to gleam / to glow (los ojos brillaban = the eyes gleamed)" },
  { sp: "pálido", en: "pale / pallid (quedarse pálido = to go pale from shock or fear)" },
  { sp: "imagen", en: "image / picture / reflection (la imagen en el espejo = the image in the mirror)" },
  { sp: "acercarse", en: "to approach / to draw near / to come closer" },
  { sp: "aseo", en: "toilet / washroom (aseos = bathrooms — Myrtle haunts the girls' aseos)" },
  { sp: "inmediatamente", en: "immediately / at once" },
  { sp: "abajo", en: "below / down / downstairs (hacia abajo = downward; boca abajo = face down)" },
  { sp: "quizá", en: "perhaps / maybe (quizá sea = perhaps it is — triggers subjunctive at C1)" },
  { sp: "muerto", en: "dead / deceased (muerto de miedo = scared to death)" },
  { sp: "abrir", en: "to open (abrir la puerta = to open the door; abrir camino = to forge a path)" },
  { sp: "caer", en: "to fall / to drop (caer al suelo = to fall to the floor; dejar caer = to drop)" },
  { sp: "diente", en: "tooth / fang (dientes de serpiente = snake fangs — the Basilisk's weapon)" },
  { sp: "último", en: "last / final / latest (el último año = the final year; por último = lastly)" },
  { sp: "fuego", en: "fire (fuego mágico = magical fire; Fawkes renace del fuego = Fawkes reborn from fire)" },
  { sp: "cielo", en: "sky / heaven (el cielo estrellado = the starry sky — Hogwarts enchanted ceiling)" },
  { sp: "lleno", en: "full / filled (lleno de miedo = filled with fear; a pleno = in full)" },
  { sp: "agua", en: "water (agua lodosa = muddy water)" },
  { sp: "piel", en: "skin / hide / fur (ponérsele la piel de gallina = to get goosebumps)" },
  { sp: "querido", en: "dear / beloved (querido diario = dear diary — Riddle's diary entries)" },
  { sp: "jaula", en: "cage (la jaula de Hedwig = Hedwig's cage)" },
  { sp: "bruja", en: "witch (bruja malvada = wicked witch; female wizard)" },
  { sp: "sitio", en: "place / spot (en este sitio = in this place; hacer sitio = to make room)" },
  { sp: "sol", en: "sun (a pleno sol = in full sun; salir el sol = for the sun to rise)" },
  { sp: "algún", en: "some / any (algún mago = some wizard; algún día = someday)" },
  { sp: "fantasma", en: "ghost (los fantasmas de Hogwarts; Nearly Headless Nick is a fantasma)" },
  { sp: "lengua", en: "tongue / language (lengua de serpiente = snake tongue; Parseltongue)" },
  { sp: "trabajo", en: "work / job / task (trabajo de clase = class assignment; trabajo duro = hard work)" },
  { sp: "callejón", en: "alley (el Callejón Diagon = Diagon Alley; el Callejón Knockturn = Knockturn Alley)" },
  { sp: "hombro", en: "shoulder (encogerse de hombros = to shrug)" },
  { sp: "persona", en: "person / individual (una persona de confianza = a trusted person)" },
  { sp: "muro", en: "wall / barrier (muro de piedra = stone wall; muro de contención = retaining wall)" },
  { sp: "extremo", en: "end / extreme / tip (al otro extremo = at the other end; en casos extremos)" },
  { sp: "aula", en: "classroom / lecture hall (aula de transformaciones = Transfiguration classroom)" },
  { sp: "sucio", en: "dirty / filthy (sangre sucia = Mudblood — HP slur for Muggle-born wizard)" },
  { sp: "realmente", en: "really / truly / in reality (B2 intensifier)" },
  { sp: "amigo", en: "friend / mate (mi mejor amigo = my best friend)" },
  { sp: "pociones", en: "Potions (school subject; la clase de Pociones = Potions class — Snape's domain)" },
  { sp: "baúl", en: "trunk / chest (el baúl de Harry = Harry's school trunk)" },
  { sp: "verde", en: "green (los ojos verdes de Harry; la marca verde = the Dark Mark in the sky)" },
  { sp: "brillante", en: "brilliant / shining / gleaming (ojos brillantes = gleaming eyes)" },
  { sp: "supuesto", en: "supposed / assumed (por supuesto = of course — essential B2 fixed phrase)" },
  { sp: "armario", en: "wardrobe / cupboard (el armario debajo de la escalera = Harry's cupboard under the stairs)" },
  { sp: "vistazo", en: "glance / quick look (echar un vistazo = to have a quick look)" },
  { sp: "prefecto", en: "prefect (student monitor at Hogwarts; Percy Weasley is a prefecto)" },
  { sp: "madre", en: "mother / mum (madre de sangre pura = pure-blood mother)" },
  { sp: "coger", en: "to grab / to take / to catch (Spain: coger la varita = to grab the wand)" },
  { sp: "tinta", en: "ink (tinta invisible = invisible ink; Riddle's diary absorbs and releases tinta)" },
  { sp: "premio", en: "prize / award (Lockhart's many Premio awards line his office walls)" },
  { sp: "rápidamente", en: "quickly / rapidly (B2 adverb of manner)" },
  { sp: "seleccionador", en: "selector / sorting agent (Sombrero Seleccionador = Sorting Hat)" },
  { sp: "demás", en: "the rest / the others (los demás alumnos = the other students)" },
  { sp: "muerte", en: "death (la Orden de la Muerte = Death Eaters; pena de muerte = death penalty)" },
  { sp: "señorita", en: "Miss / young woman (señorita Granger = Miss Granger)" },
  { sp: "fiesta", en: "party / celebration (la fiesta de Casi Decapitado = Nearly Headless Nick's deathday party)" },
  { sp: "impresión", en: "impression / shock (dar buena impresión = to make a good impression)" },
  { sp: "cumpleaños", en: "birthday (el peor cumpleaños = the worst birthday — Chapter 1 title)" },
  { sp: "seguir", en: "to follow / to continue / to keep on (seguir adelante = to keep going)" },
  { sp: "salto", en: "jump / leap (dar un salto = to leap; pegar un salto = to give a start)" },
  { sp: "verano", en: "summer (las vacaciones de verano = summer holidays)" },
  { sp: "importante", en: "important / significant (lo más importante = the most important thing)" },
  { sp: "montón", en: "heap / pile / loads (un montón de = loads of — B2 colloquial intensifier)" },
  { sp: "pierna", en: "leg (las piernas temblorosas = trembling legs)" },
  { sp: "mitad", en: "half / midpoint (a mitad de camino = halfway; la mitad del curso = mid-term)" },
  { sp: "mamá", en: "mum / mom (informal; used by the Weasley children for Mrs Weasley)" },
  { sp: "cabo", en: "end / detail (al cabo de = after; llevar a cabo = to carry out; al fin y al cabo = after all)" },
  { sp: "defensa", en: "defence (Defensa Contra las Artes Oscuras = Defence Against the Dark Arts)" },
  { sp: "velocidad", en: "speed / velocity (a toda velocidad = at full speed)" },
  { sp: "entrada", en: "entrance / entry (la entrada de la cámara = the entrance to the chamber)" },
  { sp: "difícil", en: "difficult / hard / tricky (una situación difícil = a difficult situation)" },
  { sp: "vela", en: "candle (las velas flotantes del Gran Comedor = the floating candles of the Great Hall)" },
  { sp: "bolsa", en: "bag / purse / pouch (la bolsa de galeones = the bag of Galleons)" },
  { sp: "peor", en: "worse / worst (el peor cumpleaños = the worst birthday; de mal en peor = from bad to worse)" },
  { sp: "favor", en: "favour (por favor = please; a favor de = in favour of; pedir un favor = to ask a favour)" },
  { sp: "partido", en: "match / game / party (partido de Quidditch = Quidditch match)" },
  { sp: "pájaro", en: "bird (el pájaro de fuego = the firebird — Fawkes the phoenix)" },
  { sp: "arriba", en: "above / up / upstairs (hacia arriba = upward; de arriba abajo = from top to bottom)" },
  { sp: "suficiente", en: "enough / sufficient (ya es suficiente = that's enough; suficiente para = enough to)" },
  { sp: "cocina", en: "kitchen (la cocina de los Weasley = the Weasleys' kitchen at the Burrow)" },
  { sp: "furioso", en: "furious / enraged / livid (ponerse furioso = to become furious)" },
  { sp: "vacaciones", en: "holidays / vacation (vacaciones de verano = summer holidays)" },
  { sp: "torre", en: "tower (la Torre de Gryffindor = Gryffindor Tower; la Torre de Astronomía)" },
  { sp: "cabaña", en: "hut / cabin (la cabaña de Hagrid = Hagrid's hut on Hogwarts grounds)" },
  { sp: "cicatriz", en: "scar (la cicatriz en la frente de Harry = Harry's lightning-bolt scar)" },
  { sp: "exactamente", en: "exactly / precisely (eso es exactamente = that is exactly it)" },
  { sp: "comer", en: "to eat (comer en el Gran Comedor = to eat in the Great Hall)" },
  { sp: "famoso", en: "famous / renowned (Lockhart es famoso = Lockhart is famous — for fabricated deeds)" },
  { sp: "oreja", en: "ear (outer ear; aguzar las orejas = to prick up one's ears)" },
  { sp: "punta", en: "tip / point / end (la punta de la varita = the tip of the wand)" },
  { sp: "piso", en: "floor / storey / flat (el primer piso = the first floor; vivir en un piso = to live in a flat)" },
  { sp: "poder", en: "power / ability; to be able to (el poder del basilisco = the basilisk's power)" },
  { sp: "fénix", en: "phoenix (Fawkes, Dumbledore's fénix — loyal, tears heal, reborn from ashes)" },
  { sp: "espada", en: "sword (la espada de Godric Gryffindor = Godric Gryffindor's sword — key plot weapon)" },
  { sp: "susurro", en: "whisper / murmur (un susurro en la pared = a whisper in the wall — the Basilisk)" },
  { sp: "ocupado", en: "busy / occupied (estar ocupado = to be busy; el baño está ocupado = the bathroom is occupied)" },
  { sp: "oscurecer", en: "to darken / to grow dark (el cielo empezó a oscurecer = the sky began to darken)" },
];

export type AppSeedCard = {
  front: string;
  back: string;
  tags: string[];
  extra: {
    source: "hp-chamber-of-secrets";
  };
};

const dedupeKey = (record: SeedCardRecord) =>
  `${record.sp.trim().toLowerCase()}|${record.en.trim().toLowerCase()}`;

export const FORMATTED_SEED_CARDS: AppSeedCard[] = SEED_CARD_DECK.reduce<AppSeedCard[]>((cards, record) => {
  const normalizedFront = record.sp.trim();
  const normalizedBack = record.en.trim();

  if (!normalizedFront || !normalizedBack) {
    return cards;
  }

  const key = dedupeKey(record);
  const alreadyIncluded = cards.some(
    (card) => `${card.front.trim().toLowerCase()}|${card.back.trim().toLowerCase()}` === key,
  );

  if (alreadyIncluded) {
    return cards;
  }

  cards.push({
    front: normalizedFront,
    back: normalizedBack,
    tags: ["hp-chamber-of-secrets"],
    extra: {
      source: "hp-chamber-of-secrets",
    },
  });

  return cards;
}, []);

export const TOTAL_SOURCE_CARDS = SEED_CARD_DECK.length;
export const TOTAL_FORMATTED_CARDS = FORMATTED_SEED_CARDS.length;